# Generated by Django 4.0.4 on 2022-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_customerfirstname_invoice_customerlastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customerPhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
