# Generated by Django 4.0.4 on 2022-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_customerphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
