# Generated by Django 4.0.4 on 2022-06-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesproduct',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
